blank_issues_enabled: false
contact_links:
  - name: Support Questions & Other
    url: https://github.com/aasumitro/gowa/discussions/categories/q-a
    about: 'This repository is only for reporting bugs. If you have a question or need help using the library, click:'
  - name: Documentation issue
    url: https://github.com/aasumitro/gowa/discussions/categories/wiki
    about: For documentation issues, open a pull request at the aasumitro/gowa repository